server:
  port: 8123
  servlet:
    context-path: /api
nyapi:
  client:
    access-key: xxxxx
    secret-key: xxxxx
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
